---

- name: Configure /etc/apt/apt.conf.d/20auto-upgrades
  template: >
    src="auto-upgrades.j2"
    dest="/etc/apt/apt.conf.d/20auto-upgrades"
    owner="root"
    group="root"
    mode="0644"
    backup="yes"
  
# EOF
...
