---
# linux-postinstall gpg

- name: "gpg: Install gpg packages"
  package:
    name: "{{ item }}"
  loop: "{{ lp_gpg_packages }}"
  when: (ansible_os_family == "Debian") or
        (ansible_os_family == "RedHat")

- name: "gpg: Configure ~/.gnupg/gpg.conf"
  template:
    src: "gpg.conf.j2"
    dest: "/home/{{ item.owner }}/.gnupg/gpg.conf"
    owner: "{{ item.owner }}"
    group: "{{ item.owner }}"
    mode: "0600"
    backup: yes
  loop: "{{ lp_gpg_conf_user }}"

# TODO: import keys

# EOF
...
