---
# linux-postinstall gpsd

- name: Install packages for gpsd
  apt: >
    name="{{ item }}"
    state="present"
  with_items:
    - gpsd
    - gpsd-clients
  when:
    - lp_gpsd|lower == "yes"
    - ansible_os_family == "Debian"
  tags: lp_gpsd_packages

- name: Add user gpsd to group dialout
  user: >
    name="gpsd"
    groups="dialout"
    append="yes"
  when: lp_gpsd|lower == "yes"
  tags: lp_gpsd_group

- name: Configure /etc/bluetooth/rfcomm.conf
  blockinfile:
    dest: "/etc/bluetooth/rfcomm.conf"
    marker: "# {mark} ANSIBLE MANAGED BLOCK rfcomm{{ item.rfcomm }}"
    insertafter: "EOF"
    owner: "root"
    group: "root"
    mode: "0644"
    backup: "yes"
    block: |
      rfcomm{{ item.rfcomm }} {
        bind {{ item.bind }}
        device {{ item.device }}
        channel {{ item.channel }}
        comment "{{ item.comment }}"
        }
  with_items: "{{ lp_gpsd_bt_rfcomm }}"
  notify: restart bluetooth
  tags: lp_gpsd_bt_rfcom

- name: Configure /etc/default/gpsd
  template: >
    src="gpsd.j2"
    dest="/etc/default/gpsd"
    owner="root"
    group="root"
    mode="0644"
    backup="yes"
  notify: restart gpsd
  tags: lp_gpsd_config
  
- name: Stop and disable gpsd
  systemd: >
    name="gpsd"
    state="stopped"
    enabled="no"
  when: lp_gpsd|lower == "no"
  tags: lp_gpsd_stop

- name: Start and enable gpsd
  systemd: >
    name="gpsd"
    state="started"
    enabled="yes"
  when: lp_gpsd|lower == "yes"
  tags: lp_gpsd_start

# EOF
...
