---

- name: Configure hostname in /etc/hostname
  template: >
    src="hostname.j2"
    dest="/etc/hostname"
    owner="root"
    group="root"
    mode="0644"
    backup="yes"
  when: lp_hostname|length > 0
  notify: set hostname

- name: Configure hosts in /etc/hosts
  template: >
    src="hosts.j2"
    dest="/etc/hosts"
    owner="root"
    group="root"
    mode="0644"
    backup="yes"
  when: lp_hostname|length > 0
  
# EOF
...
