---
# linux-postinstall

- include: hostname.yml
  tags:
    - lp_hostname_hosts
    - linux-postinstall

- include: modules.yml
  tags:
    - lp_modules
    - linux-postinstall

- include: sysctl.yml
  tags:
    - lp_sysctl
    - linux-postinstall

- include: udev.yml
  tags:
    - lp_udev
    - linux-postinstall

- include: iptables.yml
  when: lp_iptables == "yes"
  tags:
    - lp_iptables
    - linux-postinstall

- include: wpagui.yml
  when: lp_wpagui == "yes"
  tags:
    - lp_wpagui
    - linux-postinstall

- include: users.yml
  tags:
    - lp_users
    - linux-postinstall

- include: aliases.yml
  tags:
    - lp_aliases
    - linux-postinstall

- include: authorized_keys.yml
  tags:
    - lp_authorized_keys
    - linux-postinstall

- include: grub.yml
  tags:
    - lp_grub
    - linux-postinstall

- include: xen.yml
  when: lp_xen == "yes"
  tags:
    - lp_xen
    - linux-postinstall

- include: latex.yml
  when: lp_latex == "yes"
  tags:
    - lp_latex
    - linux-postinstall

# TODO
#- include: pm.yml
#  tags:
#    - lp_pm
#    - linux-postinstall

# EOF
...
