---
# tasks for vbotka.linux-postinstall

- include: packages.yml
  tags:
    - lp_packages
    - linux_postinstall

- include: hostname.yml
  tags:
    - lp_hostname_hosts
    - linux_postinstall

- include: modules.yml
  tags:
    - lp_modules
    - linux_postinstall

- include: sysctl.yml
  tags:
    - lp_sysctl
    - linux_postinstall

- include: udev.yml
  tags:
    - lp_udev
    - linux_postinstall

- include: iptables.yml
  when: lp_iptables|lower == "yes"
  tags:
    - lp_iptables
    - linux_postinstall

- include: wpagui.yml
  when: lp_wpagui|lower == "yes"
  tags:
    - lp_wpagui
    - linux_postinstall

- include: users.yml
  tags:
    - lp_users
    - linux_postinstall

- include: aliases.yml
  tags:
    - lp_aliases
    - linux_postinstall

- include: authorized_keys.yml
  tags:
    - lp_authorized_keys
    - linux_postinstall

- include: grub.yml
  tags:
    - lp_grub
    - linux_postinstall

- include: xen.yml
  when: lp_xen|lower == "yes"
  tags:
    - lp_xen
    - linux_postinstall

- include: latex.yml
  when: lp_latex|lower == "yes"
  tags:
    - lp_latex
    - linux_postinstall

- include: auto_upgrades.yml
  tags:
    - lp_auto_upgrades
    - linux_postinstall

- include: pm-utils.yml
  when: lp_pm|lower == "yes"
  tags:
    - lp_pm
    - linux_postinstall

- include: ssh.yml
  tags:
    - lp_ssh
    - linux_postinstall

- include: sshd.yml
  when: lp_sshd|lower == "yes"
  tags:
    - lp_sshd
    - linux_postinstall

- include: bluetooth.yml
  when: lp_bluetooth|lower == "yes"
  tags:
    - lp_bluetooth
    - linux_postinstall

- include: xorg.yml
  tags:
    - lp_xorg
    - linux_postinstall

- include: cron.yml
  tags:
    - lp_cron
    - linux_postinstall

- include: modemmanager.yml
  tags:
    - lp_modemmanager
    - linux_postinstall

- include: gpsd.yml
  tags:
    - lp_gpsd
    - linux_postinstall

- include: postfix.yml
  tags:
    - lp_postfix
    - linux_postinstall

- include: smart.yml
  tags:
    - lp_smart
    - linux_postinstall

- include: apparmor.yml
  tags:
    - lp_apparmor
    - linux_postinstall

# EOF
...
