---
# tasks linux-postinstall

- name: Debug
  vars:
    msg: |
      ansible_architecture [ {{ ansible_architecture }} ]
      ansible_os_family [ {{ ansible_os_family }} ]
      ansible_distribution [ {{ ansible_distribution }} ]
      ansible_distribution_major_version [ {{ ansible_distribution_major_version }} ]
      ansible_distribution_version [ {{ ansible_distribution_version }} ]
      ansible_distribution_release [ {{ ansible_distribution_release }} ]

      lp_apparmor [ {{ lp_apparmor }} ]
      lp_bluetooth [ {{ lp_bluetooth }} ]
      lp_gpg [ {{ lp_gpg }} ]
      lp_gpsd [ {{ lp_gpsd }} ]
      lp_iptables [ {{ lp_iptables }} ]
      lp_latex [ {{ lp_latex }} ]
      lp_lid [ {{ lp_lid }} ]
      lp_modemmanager [ {{ lp_modemmanager }} ]
      lp_netplan [ {{ lp_netplan }} ]
      lp_nfsd [ {{ lp_nfsd }} ]
      lp_packages_autoremove [ {{ lp_packages_autoremove }} ]
      lp_pm [ {{ lp_pm }} ]
      lp_postfix [ {{ lp_postfix }} ]
      lp_smart [ {{ lp_smart }} ]
      lp_speechd [ {{ lp_speechd }} ]
      lp_sshd [ {{ lp_sshd }} ]
      lp_swap [ {{ lp_swap }} ]
      lp_timesyncd [ {{ lp_timesyncd }} ]
      lp_timezone [ {{ lp_timezone }} ]
      lp_unattended_upgrades [ {{ lp_unattended_upgrades }} ]
      lp_virtualbox [ {{ lp_virtualbox }} ]
      lp_wpagui [ {{ lp_wpagui }} ]
      lp_wpasupplicant [ {{ lp_wpasupplicant }} ]
      lp_xen [ {{ lp_xen }} ]
      lp_zeitgeist [ {{ lp_zeitgeist }} ]
  debug:
    msg: "{{ msg.split('\n') }}"
  when: lp_debug|lower == "yes"
  tags:
    - lp_debug
    - linux_postinstall

- name: vars for {{ ansible_os_family }} {{ ansible_distribution }} {{ ansible_distribution_release }}
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
      paths: '{{ role_path }}/vars'
  when: (ansible_os_family == "RedHat" ) or
        (ansible_os_family == "Debian" )
  tags:
    - lp_vars
    - linux_postinstall

- import_tasks: swap.yml
  when: (ansible_os_family == "RedHat" ) or
        (ansible_os_family == "Debian" )
  tags:
    - lp_swap
    - linux_postinstall

- import_tasks: modules.yml
  when: (ansible_os_family == "RedHat" ) or
        (ansible_os_family == "Debian" )
  tags:
    - lp_modules
    - linux_postinstall

- import_tasks: udev.yml
  when: (ansible_os_family == "RedHat" ) or
        (ansible_os_family == "Debian" )
  tags:
    - lp_udev
    - linux_postinstall

- import_tasks: netplan.yml
  when:
    - ansible_os_family == "Debian"
    - lp_netplan|lower == "yes"
  tags:
    - lp_netplan
    - linux_postinstall

- import_tasks: timezone.yml
  when:
    - (ansible_os_family == "RedHat" ) or
      (ansible_os_family == "Debian" )
    - lp_timezone|lower == "yes"
  tags:
    - lp_timezone
    - linux_postinstall
  
- import_tasks: timesyncd.yml
  when: ansible_os_family == "Debian"
  tags:
    - lp_timesyncd
    - linux_postinstall

- import_tasks: repos.yml
  when: ansible_os_family == "Debian" # TODO: RH
  tags:
    - lp_repos
    - linux_postinstall

- import_tasks: packages.yml
  when: (ansible_os_family == "RedHat" ) or
        (ansible_os_family == "Debian" )
  tags:
    - lp_packages
    - linux_postinstall

- import_tasks: auto_upgrades.yml
  when: ansible_os_family == "Debian" # TODO: RH
  tags:
    - lp_auto_upgrades
    - linux_postinstall

- import_tasks: sysctl.yml
  when: (ansible_os_family == "RedHat" ) or
        (ansible_os_family == "Debian" )
  tags:
    - lp_sysctl
    - linux_postinstall

- import_tasks: hostname.yml
  when: (ansible_os_family == "RedHat" ) or
        (ansible_os_family == "Debian" )
  tags:
    - lp_hostname
    - linux_postinstall

- import_tasks: hosts.yml
  when: (ansible_os_family == "RedHat" ) or
        (ansible_os_family == "Debian" )
  tags:
    - lp_hosts
    - linux_postinstall

- import_tasks: iptables.yml
  when:
    - ansible_os_family == "Debian" # TODO: RH
    - lp_iptables|lower == "yes"
  tags:
    - lp_iptables
    - linux_postinstall

- import_tasks: grub.yml
  when: ansible_os_family == "Debian" # TODO: RH
  tags:
    - lp_grub
    - linux_postinstall
  # https://unix.stackexchange.com/questions/152222/equivalent-of-update-grub-for-rhel-fedora-centos-systems

- import_tasks: users.yml
  when: (ansible_os_family == "RedHat" ) or
        (ansible_os_family == "Debian" )
  tags:
    - lp_users
    - linux_postinstall

- import_tasks: sudoers.yml
  when: (ansible_os_family == "RedHat" ) or
        (ansible_os_family == "Debian" )
  tags:
    - lp_sudoers
    - linux_postinstall

- import_tasks: authorized_keys.yml
  when: (ansible_os_family == "RedHat" ) or
        (ansible_os_family == "Debian" )
  tags:
    - lp_authorized_keys
    - linux_postinstall

- import_tasks: aliases.yml
  when: (ansible_os_family == "RedHat" ) or
        (ansible_os_family == "Debian" )
  tags:
    - lp_aliases
    - linux_postinstall

- import_tasks: pm-utils.yml
  when:
    - ansible_os_family == "Debian" # TODO: RH
    - lp_pm|lower == "yes"
  tags:
    - lp_pm
    - linux_postinstall

- import_tasks: ssh.yml
  when: (ansible_os_family == "RedHat" ) or
        (ansible_os_family == "Debian" )
  tags:
    - lp_ssh
    - linux_postinstall

- import_tasks: sshd.yml
  when: (ansible_os_family == "RedHat" ) or
        (ansible_os_family == "Debian" )
  tags:
    - lp_sshd
    - linux_postinstall

- import_tasks: bluetooth.yml
  when:
    - ansible_os_family == "Debian"
    - lp_bluetooth|lower == "yes"
  tags:
    - lp_bluetooth
    - linux_postinstall

- import_tasks: xorg.yml
  when: ansible_os_family == "Debian"
  tags:
    - lp_xorg
    - linux_postinstall

- import_tasks: cron.yml
  when: (ansible_os_family == "RedHat" ) or
        (ansible_os_family == "Debian" )
  tags:
    - lp_cron
    - linux_postinstall

- import_tasks: modemmanager.yml
  when: ansible_os_family == "Debian"
  tags:
    - lp_modemmanager
    - linux_postinstall

- import_tasks: gpsd.yml
  when:
    - ansible_os_family == "Debian"
    - lp_gpsd|lower == "yes"
  tags:
    - lp_gpsd
    - linux_postinstall

- import_tasks: postfix.yml
  when: (ansible_os_family == "RedHat" ) or
        (ansible_os_family == "Debian" )
  tags:
    - lp_postfix
    - linux_postinstall

- import_tasks: smart.yml
  when: ansible_os_family == "Debian" # TODO: RH
  tags:
    - lp_smart
    - linux_postinstall

- import_tasks: apparmor.yml
  when: ansible_os_family == "Debian"
  tags:
    - lp_apparmor
    - linux_postinstall

- import_tasks: zeitgeist.yml
  when: ansible_os_family == "Debian"
  tags:
    - lp_zeitgeist
    - linux_postinstall

- import_tasks: lid.yml
  when:
    - ansible_os_family == "Debian"
    - lp_lid|lower == "yes"
  tags:
    - lp_lid
    - linux_postinstall

- import_tasks: speechd.yml
  when: ansible_os_family == "Debian"
  tags:
    - lp_speechd
    - linux_postinstall

- import_tasks: nfsd.yml
  when: ansible_os_family == "Debian" # TODO: RH
  tags:
    - lp_nfsd
    - linux_postinstall

- import_tasks: latex.yml
  when:
    - ansible_os_family == "Debian" # TODO: RH
    - lp_latex|lower == "yes"
  tags:
    - lp_latex
    - linux_postinstall

- import_tasks: xen.yml
  when:
    - ansible_os_family == "Debian" # TODO: RH
    - lp_xen|lower == "yes"
  tags:
    - lp_xen
    - linux_postinstall

- import_tasks: virtualbox.yml
  when:
    - ansible_os_family == "Debian"   # TODO: RH
    - lp_virtualbox|lower == "yes"
  tags:
    - lp_virtualbox
    - linux_postinstall

- import_tasks: wpagui.yml
  when:
    - ansible_os_family == "Debian"
    - lp_wpagui|lower == "yes"
  tags:
    - lp_wpagui
    - linux_postinstall

- import_tasks: wpasupplicant.yml
  when:
    - (ansible_os_family == "RedHat" ) or
      (ansible_os_family == "Debian" )
    - lp_wpasupplicant|lower == "yes"

  tags:
    - lp_wpasupplicant
    - linux_postinstall

- import_tasks: gpg.yml
  when:
    - ansible_os_family == "Debian"   # TODO: RH
    - lp_gpg|lower == "yes"
  tags:
    - lp_gpg
    - linux_postinstall

# EOF
...
