---
# tasks for linux-postinstall

- include: iptables.yml
  when: lp_iptables == "yes"
  tags:
    - lp_iptables
    - linux-postinstall

- include: wpagui.yml
  when: lp_wpagui == "yes"
  tags:
    - lp_wpagui
    - linux-postinstall

- include: sysctl.yml
  tags:
    - lp_sysctl
    - linux-postinstall

- include: udev.yml
  tags:
    - lp_udev
    - linux-postinstall

# TODO
#- include: pm.yml
#  tags:
#    - lp_pm
#    - linux-postinstall

# EOF
...
