---
# tasks linux-postinstall

- name: Debug
  vars:
    msg: |
      ansible_architecture [ {{ ansible_architecture }} ]
      ansible_os_family [ {{ ansible_os_family }} ]
      ansible_distribution [ {{ ansible_distribution }} ]
      ansible_distribution_major_version [ {{ ansible_distribution_major_version }} ]
      ansible_distribution_version [ {{ ansible_distribution_version }} ]
      ansible_distribution_release [ {{ ansible_distribution_release }} ]

      lp_apparmor [ {{ lp_apparmor }} ]
      lp_bluetooth [ {{ lp_bluetooth }} ]
      lp_gpg [ {{ lp_gpg }} ]
      lp_gpsd [ {{ lp_gpsd }} ]
      lp_iptables [ {{ lp_iptables }} ]
      lp_latex [ {{ lp_latex }} ]
      lp_lid [ {{ lp_lid }} ]
      lp_modemmanager [ {{ lp_modemmanager }} ]
      lp_netplan [ {{ lp_netplan }} ]
      lp_nfsd [ {{ lp_nfsd }} ]
      lp_packages_autoremove [ {{ lp_packages_autoremove }} ]
      lp_pm [ {{ lp_pm }} ]
      lp_postfix [ {{ lp_postfix }} ]
      lp_smart [ {{ lp_smart }} ]
      lp_speechd [ {{ lp_speechd }} ]
      lp_sshd [ {{ lp_sshd }} ]
      lp_swap [ {{ lp_swap }} ]
      lp_timesyncd [ {{ lp_timesyncd }} ]
      lp_timezone [ {{ lp_timezone }} ]
      lp_unattended_upgrades [ {{ lp_unattended_upgrades }} ]
      lp_virtualbox [ {{ lp_virtualbox }} ]
      lp_wpagui [ {{ lp_wpagui }} ]
      lp_wpasupplicant [ {{ lp_wpasupplicant }} ]
      lp_xen [ {{ lp_xen }} ]
      lp_zeitgeist [ {{ lp_zeitgeist }} ]
  debug:
    msg: "{{ msg.split('\n') }}"
  when: lp_debug
  tags: lp_debug

- name: vars for {{ ansible_os_family }} {{ ansible_distribution }} {{ ansible_distribution_release }}
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
      paths: '{{ role_path }}/vars'
  tags: lp_vars

- import_tasks: swap.yml
  when: (ansible_os_family == "RedHat" ) or
        (ansible_os_family == "Debian" )
  tags: lp_swap

- import_tasks: modules.yml
  when: (ansible_os_family == "RedHat" ) or
        (ansible_os_family == "Debian" )
  tags: lp_modules

- import_tasks: udev.yml
  when: (ansible_os_family == "RedHat" ) or
        (ansible_os_family == "Debian" )
  tags: lp_udev

- import_tasks: netplan.yml
  when:
    - ansible_os_family == "Debian"
    - lp_netplan
  tags: lp_netplan

- import_tasks: timezone.yml
  when:
    - (ansible_os_family == "RedHat" ) or
      (ansible_os_family == "Debian" )
    - lp_timezone
  tags: lp_timezone
  
- import_tasks: timesyncd.yml
  when: ansible_os_family == "Debian"
  tags: lp_timesyncd

- import_tasks: repos.yml
  when: ansible_os_family == "Debian" # TODO: RH
  tags: lp_repos

- import_tasks: packages.yml
  when: (ansible_os_family == "RedHat" ) or
        (ansible_os_family == "Debian" )
  tags: lp_packages

- import_tasks: auto_upgrades.yml
  when: ansible_os_family == "Debian" # TODO: RH
  tags: lp_auto_upgrades

- import_tasks: sysctl.yml
  when: (ansible_os_family == "RedHat" ) or
        (ansible_os_family == "Debian" )
  tags: lp_sysctl

- import_tasks: hostname.yml
  when: (ansible_os_family == "RedHat" ) or
        (ansible_os_family == "Debian" )
  tags: lp_hostname

- import_tasks: hosts.yml
  when: (ansible_os_family == "RedHat" ) or
        (ansible_os_family == "Debian" )
  tags: lp_hosts

- import_tasks: iptables.yml
  when:
    - ansible_os_family == "Debian" # TODO: RH
    - lp_iptables
  tags: lp_iptables

- import_tasks: grub.yml
  when: ansible_os_family == "Debian" # TODO: RH
  tags: lp_grub
  # https://unix.stackexchange.com/questions/152222/equivalent-of-update-grub-for-rhel-fedora-centos-systems

- import_tasks: users.yml
  when: (ansible_os_family == "RedHat" ) or
        (ansible_os_family == "Debian" )
  tags: lp_users

- import_tasks: sudoers.yml
  when: (ansible_os_family == "RedHat" ) or
        (ansible_os_family == "Debian" )
  tags: lp_sudoers

- import_tasks: authorized_keys.yml
  when: (ansible_os_family == "RedHat" ) or
        (ansible_os_family == "Debian" )
  tags: lp_authorized_keys

- import_tasks: aliases.yml
  when: (ansible_os_family == "RedHat" ) or
        (ansible_os_family == "Debian" )
  tags: lp_aliases

- import_tasks: pm-utils.yml
  when:
    - ansible_os_family == "Debian" # TODO: RH
    - lp_pm
  tags: lp_pm

- import_tasks: ssh.yml
  when: (ansible_os_family == "RedHat" ) or
        (ansible_os_family == "Debian" )
  tags: lp_ssh

- import_tasks: sshd.yml
  when: (ansible_os_family == "RedHat" ) or
        (ansible_os_family == "Debian" )
  tags: lp_sshd

- import_tasks: bluetooth.yml
  when:
    - ansible_os_family == "Debian"
    - lp_bluetooth
  tags: lp_bluetooth

- import_tasks: xorg.yml
  when: ansible_os_family == "Debian"
  tags: lp_xorg

- import_tasks: cron.yml
  when: (ansible_os_family == "RedHat" ) or
        (ansible_os_family == "Debian" )
  tags: lp_cron

- import_tasks: modemmanager.yml
  when: ansible_os_family == "Debian"
  tags: lp_modemmanager

- import_tasks: gpsd.yml
  when:
    - ansible_os_family == "Debian"
    - lp_gpsd
  tags: lp_gpsd

- import_tasks: postfix.yml
  when: (ansible_os_family == "RedHat" ) or
        (ansible_os_family == "Debian" )
  tags: lp_postfix

- import_tasks: smart.yml
  when: ansible_os_family == "Debian" # TODO: RH
  tags: lp_smart

- import_tasks: apparmor.yml
  when: ansible_os_family == "Debian"
  tags: lp_apparmor

- import_tasks: zeitgeist.yml
  when: ansible_os_family == "Debian"
  tags: lp_zeitgeist

- import_tasks: lid.yml
  when:
    - ansible_os_family == "Debian"
    - lp_lid
  tags: lp_lid

- import_tasks: speechd.yml
  when: ansible_os_family == "Debian"
  tags: lp_speechd

- import_tasks: nfsd.yml
  when: ansible_os_family == "Debian" # TODO: RH
  tags: lp_nfsd

- import_tasks: latex.yml
  when:
    - ansible_os_family == "Debian"  # TODO: RH
    - lp_latex
  tags: lp_latex

- import_tasks: xen.yml
  when:
    - ansible_os_family == "Debian" # TODO: RH
    - lp_xen
  tags: lp_xen

- import_tasks: virtualbox.yml
  when:
    - ansible_os_family == "Debian"   # TODO: RH
    - lp_virtualbox
  tags: lp_virtualbox

- import_tasks: wpagui.yml
  when:
    - ansible_os_family == "Debian"
    - lp_wpagui
  tags: lp_wpagui

- import_tasks: wpasupplicant.yml
  when:
    - (ansible_os_family == "RedHat" ) or
      (ansible_os_family == "Debian" )
    - lp_wpasupplicant
  tags: lp_wpasupplicant

- import_tasks: gpg.yml
  when:
    - ansible_os_family == "Debian"   # TODO: RH
    - lp_gpg
  tags: lp_gpg

- import_tasks: logrotate.yml
  when:
    - (ansible_os_family == "RedHat" ) or
      (ansible_os_family == "Debian" )
  tags: lp_logrotate

# EOF
...
