---
# tasks for vbotka.linux-postinstall

- debug:
    msg: "lp_virtualbox={{ lp_virtualbox }}
          lp_iptables={{ lp_iptables }}
          lp_wpagui={{ lp_wpagui }}
          lp_pm={{ lp_pm }}
          lp_xen={{ lp_xen }}"
  when: lp_debug|lower == "yes"
  tags:
    - lp_debug
    - linux_postinstall

- import_tasks: packages.yml
  tags:
    - lp_packages
    - linux_postinstall

- import_tasks: virtualbox.yml
  when: lp_virtualbox|lower == "yes"
  tags:
    - lp_virtualbox
    - linux_postinstall

- import_tasks: hostname.yml
  tags:
    - lp_hostname_hosts
    - linux_postinstall

- import_tasks: modules.yml
  tags:
    - lp_modules
    - linux_postinstall

- import_tasks: sysctl.yml
  tags:
    - lp_sysctl
    - linux_postinstall

- import_tasks: udev.yml
  tags:
    - lp_udev
    - linux_postinstall

- import_tasks: iptables.yml
  when: lp_iptables|lower == "yes"
  tags:
    - lp_iptables
    - linux_postinstall

- import_tasks: wpagui.yml
  when: lp_wpagui|lower == "yes"
  tags:
    - lp_wpagui
    - linux_postinstall

- import_tasks: users.yml
  tags:
    - lp_users
    - linux_postinstall

- import_tasks: aliases.yml
  tags:
    - lp_aliases
    - linux_postinstall

- import_tasks: authorized_keys.yml
  tags:
    - lp_authorized_keys
    - linux_postinstall

- import_tasks: grub.yml
  tags:
    - lp_grub
    - linux_postinstall

- import_tasks: xen.yml
  when: lp_xen|lower == "yes"
  tags:
    - lp_xen
    - linux_postinstall

- import_tasks: latex.yml
  when: lp_latex|lower == "yes"
  tags:
    - lp_latex
    - linux_postinstall

- import_tasks: auto_upgrades.yml
  tags:
    - lp_auto_upgrades
    - linux_postinstall

- import_tasks: pm-utils.yml
  when: lp_pm|lower == "yes"
  tags:
    - lp_pm
    - linux_postinstall

- import_tasks: ssh.yml
  tags:
    - lp_ssh
    - linux_postinstall

- import_tasks: sshd.yml
  when: lp_sshd|lower == "yes"
  tags:
    - lp_sshd
    - linux_postinstall

- import_tasks: bluetooth.yml
  when: lp_bluetooth|lower == "yes"
  tags:
    - lp_bluetooth
    - linux_postinstall

- import_tasks: xorg.yml
  tags:
    - lp_xorg
    - linux_postinstall

- import_tasks: cron.yml
  tags:
    - lp_cron
    - linux_postinstall

- import_tasks: modemmanager.yml
  tags:
    - lp_modemmanager
    - linux_postinstall

- import_tasks: gpsd.yml
  tags:
    - lp_gpsd
    - linux_postinstall

- import_tasks: postfix.yml
  tags:
    - lp_postfix
    - linux_postinstall

- import_tasks: smart.yml
  tags:
    - lp_smart
    - linux_postinstall

- import_tasks: apparmor.yml
  tags:
    - lp_apparmor
    - linux_postinstall

# EOF
...
