---
# tasks file for ansible-linux-postinstall

- include: wpagui.yml
  tags:
    - lp_wpagui
    - linux-postinstall

- include: sysctl.yml
  tags:
    - lp_sysctl
    - linux-postinstall

- include: udev.yml
  tags:
    - lp_udev
    - linux-postinstall
