---
# linux-postinstall nfsd

- debug:
    msg: "lp_nfsd={{ lp_nfsd }}"
  when: lp_debug|lower == "yes"

- name: Configure exports
  template:
    src: exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: 0644
  notify: reload nfsd

- name: Enable and start nfsd services
  systemd: >
    name="{{ item }}"
    enabled="yes"
    state="started"
  with_items: "{{ lp_nfsd_services }}"
  when:
    - lp_nfsd|lower == "yes"
    - lp_nfsd_services > 0

- name: Stop and disable nfsd services
  systemd: >
    name="{{ item }}"
    enabled="no"
    state="stopped"
  with_items: "{{ lp_nfsd_services }}"
  when:
    - lp_nfsd|lower == "no"
    - lp_nfsd_services > 0

- meta: flush_handlers

# EOF
...
