---
# linux-postinstall packages

- name: Configure package selections before Install/Remove
  dpkg_selections: >
    name="{{ item.name }}"
    selection="{{ item.selection }}"
  with_items: "{{ lp_packages_selections_preinstall }}"
  when: ansible_os_family == "Debian"
  tags: lp_packages_selections_preinstall

- name: Install packages
  apt: >
    name="{{ item }}"
    state="present"
  with_items: "{{ lp_packages_install }}"
  when: ansible_os_family == "Debian"
  tags: lp_packages_install

- name: Remove packages
  apt: >
    name="{{ item }}"
    state="absent"
    autoremove="{{ lp_packages_autoremove }}"
  with_items: "{{ lp_packages_remove }}"
  when: ansible_os_family == "Debian"
  tags: lp_packages_remove

- name: Configure package selections after Install/Remove
  dpkg_selections: >
    name="{{ item.name }}"
    selection="{{ item.selection }}"
  with_items: "{{ lp_packages_selections_postinstall }}"
  when: ansible_os_family == "Debian"
  tags: lp_packages_selections_postinstall

# EOF
...
