---
# linux-postinstall smart

- name: Install packages
  apt: >
    name="{{ item }}"
    state="installed"
  with_items: "{{ lp_smart_packages }}"
  when: lp_smart|lower == "yes"
  tags: lp_smart_packages

- name: Configure {{ lp_smart_conf_file }}. Do not scan for devices.
  lineinfile: >
    dest="{{ lp_smart_conf_file }}"
    regexp="^DEVICESCAN"
    state="absent"
    create="yes"
    owner="{{ lp_smart_conf_owner }}"
    group="{{ lp_smart_conf_group }}"
    mode="{{ lp_smart_conf_mode }}"
    backup="yes"
  when: lp_smart_devicescan|lower == "no"
  notify: reload smart
  tags: lp_smart_conf

- name: Configure devices in {{ lp_smart_conf_file }}
  lineinfile: >
    dest="{{ lp_smart_conf_file }}"
    regexp="{{ item.regexp }}"
    line="{{ item.line }}"
    create="yes"
    owner="{{ lp_smart_conf_owner }}"
    group="{{ lp_smart_conf_group }}"
    mode="{{ lp_smart_conf_mode }}"
    backup="yes"
  with_items: "{{ lp_smart_devices }}"
  notify: reload smart
  tags: lp_smart_conf

- name: Start and enable smart
  service: >
    name="{{ lp_smart_service_name }}"
    state="started"
    enabled="yes"
  when: lp_smart|lower == "yes"
  tags: lp_smart_service

- name: Stop and disable smart
  service: >
    name="{{ lp_smart_service_name }}"
    state="stopped"
    enabled="no"
  when: lp_smart|lower == "no"
  tags: lp_smart_service

# EOF
...
