---
# linux-postinstall sysctl

- name: "sysctl: Configure /etc/sysctl.conf"
  lineinfile:
    dest: "/etc/sysctl.conf"
    regexp: "^{{ item.var }}"
    line: "{{ item.var }} = {{ item.value }}"
    backup: yes
  with_items: "{{ lp_sysctl_vars }}"
  notify: load sysctl settings

# EOF
...
