---

- name: Add or update users
  user: >
    name="{{ item.name }}"
    shell="{{ item.shell | default(omit) }}"
    password="{{ item.password | default(omit) }}"
    update_password="{{ item.update_password | default(omit) }}"
  with_items: "{{ lp_users }}"

- name: Add users to additional groups
  user: >
    name="{{ item.name }}"
    groups="{{ item.groups }}"
    append="yes"
  with_items: "{{ lp_users_groups }}"

#  EOF
...
