---
# linux-postinstall virtualbox

- name: Debug
  vars:
    msg: |
      ansible_lsb.description [ {{ ansible_lsb.codename }} ]
      lp_virtualbox_ignore_errors [ {{ lp_virtualbox_ignore_errors }} ]
      lp_virtualbox_keys [ {{ lp_virtualbox_keys }} ]
      lp_virtualbox_repos [ {{ lp_virtualbox_repos }} ]
      lp_virtualbox_install [ {{ lp_virtualbox_install }} ]
  debug:
    msg: "{{ msg.split('\n') }}"
  when: lp_debug|lower == "yes"
  tags:
    - lp_debug
    - linux_postinstall

- name: Add signing key of VirtualBox
  apt_key: >
    url="{{ item }}"
    state="present"
  with_items: "{{ lp_virtualbox_keys }}"
  ignore_errors: "{{ lp_virtualbox_ignore_errors }}"
  when: ansible_os_family == "Debian"

- name: Add repository of VirtualBox
  apt_repository: >
    repo="{{ item }}"
    state="present"
  with_items: "{{ lp_virtualbox_repos }}"
  ignore_errors: "{{ lp_virtualbox_ignore_errors }}"
  when: ansible_os_family == "Debian"

- name: Install VirtualBox
  apt: >
    name="{{ item }}"
    state="present"
  with_items: "{{ lp_virtualbox_install }}"
  ignore_errors: "{{ lp_virtualbox_ignore_errors }}"
  when: ansible_os_family == "Debian"

# EOF
...
