---
# linux-postinstall wpa_gui
#
# Disable NetwotkManager (NM) and install wpa_gui

- name: Install packages
  apt: name="{{item}}" state="installed"
  with_items:
    - wpagui
    - wpasupplicant
  tags: linux_postinstall_wpagui_packages

- name: Disable NM /etc/init/network-manager.override
  shell: "echo manual > /etc/init/network-manager.override"
  tags: linux_postinstall_wpagui_disableNM
  
- name: Configure managed=false in /etc/NetworkManager/NetworkManager.conf
  lineinfile: dest="/etc/NetworkManager/NetworkManager.conf" regexp="^managed" line="managed=false"
  tags: linux_postinstall_wpagui_configNM

- name: Stop and disable NM
  service: name="network-manager" state="stopped" enabled="no"
