---

- name: "wpasupplicant: Debug"
  vars:
    msg: |
      lp_package_state [ {{ lp_package_state }} ]
      lp_wpasupplicant_packages [ {{ lp_wpasupplicant_packages }} ]
      lp_wpasupplicant_conf_dir [ {{ lp_wpasupplicant_conf_dir }} ]
      lp_wpasupplicant_conf_file [ {{ lp_wpasupplicant_conf_file }} ]
      lp_wpasupplicant_conf_owner [ {{ lp_wpasupplicant_conf_owner }} ]
      lp_wpasupplicant_conf_group [ {{ lp_wpasupplicant_conf_group }} ]
      lp_wpasupplicant_conf_mode [ {{ lp_wpasupplicant_conf_mode }} ]
      lp_wpasupplicant_conf_ctrl_interface [ {{ lp_wpasupplicant_conf_ctrl_interface }} ]
      lp_wpasupplicant_conf_global
      {{  lp_wpasupplicant_conf_global | to_yaml }}
      lp_wpasupplicant_conf
      {{  lp_wpasupplicant_conf | to_yaml }}
  debug:
    msg: "{{ msg.split('\n') }}"
  when: lp_wpasupplicant_debug

- name: "wpasupplicant: Install packages"
  package:
    name: "{{ item }}"
    state: "{{ lp_package_state }}"
  with_items: "{{ lp_wpasupplicant_packages }}"
  tags: lp_wpasupplicant_packages

- name: "wpasupplicant: Configure {{ lp_wpasupplicant_conf_dir }}/{{ lp_wpasupplicant_conf_file }}.DEV"
  template:
    src: "wpa_supplicant.conf.j2"
    dest: "{{ lp_wpasupplicant_conf_dir }}/{{ lp_wpasupplicant_conf_file }}.{{ item.dev }}"
    owner: "{{ lp_wpasupplicant_conf_owner }}"
    group: "{{ lp_wpasupplicant_conf_group }}"
    mode: "{{ lp_wpasupplicant_conf_mode }}"
    backup: yes
  register: wpa_supplicant_conf
  with_items: "{{ lp_wpasupplicant_conf }}"
  tags: lp_wpasupplicant_conf

- name: "wpasupplicant: Debug: registered to wpa_supplicant_conf"
  debug: msg="{{ wpa_supplicant_conf }}"
  when: lp_wpasupplicant_debug

- name: "wpasupplicant: Debug: wpa_cli reconfigure commands"
  debug:
    msg: 'sh -c "[ -S {{ lp_wpasupplicant_conf_ctrl_interface }}/{{ item.item.dev }} ] && wpa_cli -p {{ lp_wpasupplicant_conf_ctrl_interface }} -i {{ item.item.dev }} reconfigure"'
  with_items: "{{ wpa_supplicant_conf.results }}"
  when:
    - item.changed
    - lp_wpasupplicant_debug

- name: "wpasupplicant: Reconfigure wpa_supplicant"
  shell: "[ -S {{ lp_wpasupplicant_conf_ctrl_interface }}/{{ item.item.dev }} ] && wpa_cli -p {{ lp_wpasupplicant_conf_ctrl_interface }} -i {{ item.item.dev }} reconfigure  || exit 0"
  when: item.changed
  with_items: "{{ wpa_supplicant_conf.results }}"
  tags: lp_wpasupplicant_handler
  # TODO: Wait for OK result. Error: 'RECONFIGURE' command timed out.
  
# EOF
...
