---
# handlers for ansible-linux-postinstall

- name: load sysctl settings
  command: "/sbin/sysctl -p /etc/sysctl.conf"

- name: reload iptables
  shell: "/sbin/iptables-restore < /etc/network/iptables"

- name: restart udev
  systemd: name="udev" state="restarted"

- name: reload udev
# service: name="udev", state="reloaded"
  command: "/sbin/udevadm control --reload-rules"

- name: newaliases
  command: newaliases

- name: set hostname
  command: "/sbin/sysctl kernel.hostname={{ hostname }}"

- name: update grub
  command: "/usr/sbin/update-grub"

- name: reload sshd
  systemd: name="ssh" state="reloaded"

# EOF
...
