---
# handlers for vbotka.linux-postinstall

- name: load sysctl settings
  command: "/sbin/sysctl -p /etc/sysctl.conf"

- name: reload iptables
  shell: "/sbin/iptables-restore < /etc/network/iptables"

- name: newaliases
  command: newaliases

- name: set hostname
  command: "/sbin/sysctl kernel.hostname={{ hostname }}"

- name: update grub
  command: "/usr/sbin/update-grub"

- name: reload udev
  systemd: name="udev", state="reloaded"
# command: "/sbin/udevadm control --reload-rules"

- name: restart udev
  systemd: name="udev" state="restarted"

- name: reload sshd
  systemd: name="ssh" state="reloaded"
  when: lp_sshd|lower == "yes"

- name: restart bluetooth
  systemd: name="bluetooth" state="restarted"
  when: lp_bluetooth|lower == "yes"

- name: restart gpsd
  systemd: name="gpsd" state="restarted"
  when: lp_gpsd|lower == "yes"

- name: restart postfix
  systemd: name="postfix" state="restarted"
  when: lp_postfix|lower == "yes"

# EOF
...
